x_0=1, Size(feet^2), number of bedrooms, number of floors, Age of home(years), Price($1000)

In [42]:
import numpy as np

In [2]:
x = np.array([1,-1,2])

In [3]:
y = x>0
type(y)

numpy.ndarray

trick: boolean -> int 

In [4]:
y.astype(np.int)

array([1, 0, 1])

In [5]:


x0 = np.ones(4)
X = np.array([x0, [2104, 1416, 1534, 852], [1,2,2,1],[45,40,30,36], [460, 232,315,178]])
X = X.T
y = np.array([460, 232, 315, 178]).reshape(4,1)

In [6]:
y.shape

(4, 1)

In [7]:
X

array([[1.000e+00, 2.104e+03, 1.000e+00, 4.500e+01, 4.600e+02],
       [1.000e+00, 1.416e+03, 2.000e+00, 4.000e+01, 2.320e+02],
       [1.000e+00, 1.534e+03, 2.000e+00, 3.000e+01, 3.150e+02],
       [1.000e+00, 8.520e+02, 1.000e+00, 3.600e+01, 1.780e+02]])

In [8]:
# X.T@X 等价于 X.T.dot(X)
A = np.dot(X.T, X)

In [9]:
X.T@X

array([[4.000000e+00, 5.906000e+03, 6.000000e+00, 1.510000e+02,
        1.185000e+03],
       [5.906000e+03, 9.510932e+06, 8.856000e+03, 2.280120e+05,
        1.931218e+06],
       [6.000000e+00, 8.856000e+03, 1.000000e+01, 2.210000e+02,
        1.732000e+03],
       [1.510000e+02, 2.280120e+05, 2.210000e+02, 5.821000e+03,
        4.583800e+04],
       [1.185000e+03, 1.931218e+06, 1.732000e+03, 4.583800e+04,
        3.963330e+05]])

In [10]:
## inverse matrix A
A_inverse = np.linalg.inv(A)
A_inverse.shape

(5, 5)

In [11]:
theta = A_inverse@X.T@y
theta

array([[-1.97200000e+03],
       [-1.60156250e-01],
       [ 5.38875000e+02],
       [ 2.40546875e+01],
       [ 5.73242188e+00]])

In [12]:
x=np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [13]:
theta1 = np.array([100,0.1])

In [14]:
np.dot(x, theta1)

array([100.2, 300.4])

In [15]:
np.dot(theta1.T, x)

array([100.3, 200.4])

In [16]:
def sigmod(z):
    return 1 / (1 + np.exp(-z))

In [17]:
y_predict = sigmod(np.dot(X, theta))

In [18]:
y_predict

array([[1.],
       [1.],
       [1.],
       [1.]])

In [19]:
car = {}
car.setdefault('model','MINI MINI ONE')

'MINI MINI ONE'

In [20]:
car

{'model': 'MINI MINI ONE'}

__多维矩阵运算__
    + 1D
    + 2d
+ dim and shape
+ add, multiply
  

In [21]:
_1D = np.array([1,2,3,4,5,6])

In [22]:
np.ndim(_1D)

1

In [23]:
np.shape(_1D)  # tuple

(6,)

In [24]:
_1D.shape[0]

6

In [25]:
_2D = np.array([[1,2],[3,4],[5,6]]) # 3 rows, 2 columns -> 3 data, 2 attributes

In [26]:
_2D  

array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
np.ndim(_2D)

2

In [28]:
_2D.shape #(row, column)

(3, 2)

In [29]:
_2D.shape[0]

3

In [30]:
_2D[2] #第３笔数据

array([5, 6])

In [31]:
w2 = np.array([[7,8],[9,10]])

In [32]:
dot_2D = np.dot(_2D, w) # (3,2) x (2,2) = (3,2)

NameError: name 'w' is not defined

In [ ]:
dot_2D

**Trick: 1D array inner product**
 - inner product : $$ a\times b = \mid a \mid \mid b \mid \cos(\theta) $$
 ![alt text](./innerprod.gif)

In [ ]:
w1 = np.array([[7],[8],[9],[10],[11],[12]])
np.shape(w1)

In [ ]:
w1 = np.array([7,8,9,10,11,12])  #(6,)

In [ ]:
# * w1可以由 1D array 然后reshape(row, column)
w1_reshape=w1.reshape((6,1))
w1_reshape.shape 

In [ ]:
dot_1D = np.dot(_1D, w1) # shape: (6,) * (6，) = a number
dot_1D

In [ ]:
dot_1D_2 = np.dot(_1D, w1_reshape)  # shape: (6,) * (6,1) = (1,)
dot_1D_2

In [ ]:
_1Drp = _1D.reshape((1,6)) 

In [ ]:
dot_1D_3 = np.dot(_1Drp, w1)  # shape: (1,6) * (6,) = (1,)
dot_1D_3

In [ ]:
dot_1D_2.shape

In [ ]:
dot_1D_4 = np.dot(_1Drp, w1_reshape) # shape: (1,6) * (6,1) = (1,1)
dot_1D_4

In [ ]:
dot_1D_4.shape

**Summary:**  Dot product for 1D array
> 1D array　与　1D　array has to be same size
 - (size,) and (size,)  -> a value

> 1D array 与　1D Matrix: 1Dmaxtix's one size has to be same as 1D array
  - (size, ) and (size,1) -> (1,)  a 1D array
  - (size, ) and (1, size) -> (1,) a 1D array

> 1D matix 与　1D Matrix: let 1D maxtix's column size has to be same as right 1D matrix's row size
  - (x, size) and (size, y) -> (1,1) A 1D matrix

 

In [ ]:
np.dot(np.array([3,1]), np.array([1,2]))

In [ ]:
np.dot(np.array([3,1]), np.array([-1,5]))

In [ ]:
_1D

In [ ]:
# 返回array最大值的ｉndex
np.argmax(_1D)

In [ ]:
np.argmax(_2D, axis =1) # 每行的最大值的ｉndex

In [ ]:
_2D.shape

In [ ]:
for i, row in enumerate(_2D):
    print(i, type(row))

In [ ]:
_1Drp * _1Drp  # (1,6) * (1,6) 是size相同的乘法, 对应相乘

In [ ]:
_1Drp.size

In [33]:
mask = np.random.rand(3)>0.5

In [34]:
mask

array([False,  True, False])

In [35]:
x = np.random.rand(3)

In [36]:
x * mask

array([0.        , 0.25280531, 0.        ])

In [37]:
### 四维矩阵

x = np.random.rand(10,1,28,28)
x.shape

(10, 1, 28, 28)

In [38]:
x[0].shape

(1, 28, 28)

In [39]:
x[8].shape #第９笔资料

(1, 28, 28)

In [41]:
#地９个资料的第一个色版空间
x[8][0].shape

(28, 28)